service: serverless-springboot-lambda
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: java11
  timeout: 30
package:
  artifact: target/demo-0.0.1-SNAPSHOT.jar
functions:
  hello:
    handler: com.example.demo.hanlder.HelloHandler
