service: serverless-springboot-lambda

custom:
  csvBucket: serverless-springboot-lambda-csv

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: java11
  timeout: 30

package:
  artifact: target/demo-0.0.2-SNAPSHOT.jar

functions:
  hello:
    handler: com.example.demo.handler.hello.HelloHandler
    memorySize: 128
  csv:
    handler: com.example.demo.handler.csv.CsvHandler
    memorySize: 512
    events:
      - s3:
          bucket: ${self:custom.csvBucket}
