service: serverless-springboot-lambda

custom:
  csvBucket: serverless-springboot-lambda-csv

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: java11
  timeout: 30

package:
  individually: true

layers:
  common:
    package:
      artifact: common/target/common-0.0.2-SNAPSHOT.zip
    retain: false

functions:
  hello:
    handler: com.zydmayday.demo.handler.hello.HelloHandler
    memorySize: 128
    package:
      artifact: hello/target/hello-0.0.2-SNAPSHOT.jar
    layers:
      - !Ref CommonLambdaLayer
  csv:
    handler: com.zydmayday.demo.handler.csv.CsvHandler
    memorySize: 512
    package:
      artifact: csv/target/csv-0.0.2-SNAPSHOT.jar
    events:
      - s3:
          bucket: ${self:custom.csvBucket}
